# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven and Publish

on:
  push:
    tags:
      - "v*.*.*"
      - "V*.*.*"
      - "test-*"

jobs:
  build:
    strategy:
      matrix:
        version: [ 21, 22 ]
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - name: Clone Github Repo Action
      # You may pin to the exact commit or the version.
      # uses: GuillaumeFalourd/clone-github-repo-action@19817562c346ff60f9935158dede6c5ece8fd0ac
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        # Repository Owner
        owner: WuzhouDictionary
        # Repository name
        repository: ConnectToGitHub
        # PAT with repository scope (https://github.com/settings/tokens)
        access-token: ${{ secrets.GITEE_TOKEN }}
        # Depth of the clone (default: full history)
        depth: 100
        # Branch name (default: main)
        branch: main
        # Clone with submodules
        submodule: false
    - name: move to its part
      run: |
        copy-item -path ".\\ConnectToGitHub" -destination ".\\src\\main\\java\\top\\mryan2005\\managesysteminjava\\ConnectToNet"
        remove-item  ".\\ConnectToGitHub\\*"
    - name: Set up JDK ${{ matrix.version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.version }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package -Dfile.encoding=GBK -Dsun.stdout.encoding=GBK -Dsun.stderr.encoding=GBK -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true -DskipTests=true

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4

    - name: rename jar
      run: |
        rename-item "target\\DictSystemInJava-latest.jar" -newname "target\DictSystemInJava-jdk${{ matrix.version }}.jar"

    - name: create github release
      if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/V')
      uses: softprops/action-gh-release@v2.0.8
      with:
        tag_name: ${{github.github_sha}}
        name: ${{github.github_sha}}
        files: |
          D:\a\ManageSystemInJava\ManageSystemInJava\target\DictSystemInJava-jdk${{ matrix.version }}.jar
        make_latest: true
        draft: false
        prerelease: false
        token: ${{ secrets.GITEE_TOKEN }}

    - name: create github release
      if: startsWith(github.ref, 'refs/tags/test-')
      uses: softprops/action-gh-release@v2.0.8
      with:
        tag_name: ${{github.github_sha}}
        name: ${{github.github_sha}}
        files: |
          D:\a\ManageSystemInJava\ManageSystemInJava\target\DictSystemInJava-jdk${{ matrix.version }}.jar
        make_latest: false
        draft: false
        prerelease: true
        token: ${{ secrets.GITEE_TOKEN }}