# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 21, 22 ]
    steps:
    - uses: actions/checkout@v4
    - name: Clone Github Repo Action
      # You may pin to the exact commit or the version.
      # uses: GuillaumeFalourd/clone-github-repo-action@19817562c346ff60f9935158dede6c5ece8fd0ac
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        # Repository Owner
        owner: WuzhouDictionary
        # Repository name
        repository: NewIssue
        # PAT with repository scope (https://github.com/settings/tokens)
        access-token: ${{ secrets.GITEE_TOKEN }}
        # Depth of the clone (default: full history)
        depth: 100
        # Branch name (default: main)
        branch: main
        # Clone with submodules
        submodule: false
    - name: move to its part
      run: |
        mv ./NewIssue/* ./src/main/java/top/mryan2005/managesysteminjava/ConnectToNet/
        rm -rf ./NewIssue
    - name: Set up JDK ${{ matrix.version }}
      uses: actions/setup-java@v4
      with:
        java-version: '${{ matrix.version }}'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dfile.encoding=GBK -Dsun.stdout.encoding=GBK -Dsun.stderr.encoding=GBK
    - name: rename jar
      run: |
        mv target/DictSystemInJava-latest.jar target/DictSystemInJava-jdk${{ matrix.version }}.jar
        ls target
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v4

